# This is a basic workflow to help you get started with Actions
name: Copy mc_core Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key_path: id_rsa_docker_pass
          passphrase: ${{ secrets.PASSPHRASE_DOCKER }}
          #port: ${{ secrets.PORT }}
          source: "/Users/dockerimagehost/CONTENT/mc_core.tar"
          target: "mc_core"

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
        #run: scp ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/Users/dockerimagehost/CONTENT/mc_core.tar .

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
